[package]
name = "ifstat-rs"
version = "1.0.0"
authors = ["spezifisch <spezifisch+JOKING@gmail.com>"]
edition = "2018"
description = "ifstat-rs: A tool to report network interface statistics."
repository = "https://github.com/spezifisch/ifstat-rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1"
clap = { version = "3.0", features = ["derive"] }
lazy_static = "1.4"

[build-dependencies]
vergen = "6"
