[package]
name = "ifstat-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1"
clap = { version = "3.0", features = ["derive"] }
vergen = "6"
