name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install target
        run: rustup target add "${{ matrix.target }}"

      - name: Install cross
        run: cargo install cross

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y gcc-multilib g++-multilib

      - name: Set environment variables
        run: |
          # build target for rust
          echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
          # define these as 0 to skip them; these being in `var` means you'll
          # have to setup an environment with env vars in Github's repo settings
          echo "BUILD_MAC=${{ vars.BUILD_MAC }}" >> $GITHUB_ENV
          echo "BUILD_WINDOWS=${{ vars.BUILD_WINDOWS }}" >> $GITHUB_ENV

      - name: Show config for debug purposes
        run: cargo tree

      - name: Build and Test on Linux
        if: runner.os == "Linux"
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.target }}" != "x86_64-unknown-linux-gnu" ]; then
            cross build --release --target ${{ matrix.target }}
            cross test --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
            cargo test --release --target ${{ matrix.target }}
          fi

      - name: Build and Test on macOS
        if: runner.os == "macOS" && ${{ env.BUILD_MAC }} != "0"
        run: |
          if [ "${{ matrix.target }}" == "aarch64-apple-darwin" ]; then
            cross build --release --target ${{ matrix.target }}
            cross test --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
            cargo test --release --target ${{ matrix.target }}
          fi

      - name: Build and Test on Windows
        if: runner.os == "Windows" && ${{ env.BUILD_WIN }} != "0"
        run: |
          cargo build --release --target ${{ matrix.target }}
          cargo test --release --target ${{ matrix.target }}

      - name: Run program on Linux (only native)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          timeout 60s ./target/${{ matrix.target }}/release/ifstat-rs -V
          timeout 60s ./target/${{ matrix.target }}/release/ifstat-rs --version
          timeout 60s ./target/${{ matrix.target }}/release/ifstat-rs -a 0 1

      - name: Run program on macOS
        if: runner.os == "macOS" && ${{ env.BUILD_MAC }} != "0"
        run: |
          brew install coreutils
          gtimeout 60s ./target/${{ matrix.target }}/release/ifstat-rs -V
          gtimeout 60s ./target/${{ matrix.target }}/release/ifstat-rs --version
          gtimeout 60s ./target/${{ matrix.target }}/release/ifstat-rs -a 0 1

      - name: Run program on Windows
        if: runner.os == "Windows" && ${{ env.BUILD_WIN }} != "0"
        run: |
          Start-Process -FilePath "timeout.exe" -ArgumentList "60" -Wait -NoNewWindow
          ./target/${{ matrix.target }}/release/ifstat-rs.exe -V
          Start-Process -FilePath "timeout.exe" -ArgumentList "60" -Wait -NoNewWindow
          ./target/${{ matrix.target }}/release/ifstat-rs.exe --version
          Start-Process -FilePath "timeout.exe" -ArgumentList "60" -Wait -NoNewWindow
          ./target/${{ matrix.target }}/release/ifstat-rs.exe -a 0 1
