name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - riscv64gc-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-pc-windows-gnu
          - aarch64-pc-windows-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build
        run: cross build --release --target ${{ matrix.target }}

      - name: Run tests
        run: cross test --release --target ${{ matrix.target }}

      - name: Run program on native architecture
        run: |
          if [ ${{ matrix.target }} == "x86_64-unknown-linux-gnu" ]; then
            ./target/${{ matrix.target }}/release/ifstat-rs -V
            ./target/${{ matrix.target }}/release/ifstat-rs --version
            ./target/${{ matrix.target }}/release/ifstat-rs -a 0 1
          fi
        if: runner.os == 'Linux'
