name: builds
# The job of this script is to check if it builds on all platforms.
# We cross-compile from Linux.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install target
        run: rustup target add "${{ matrix.target }}"

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y gcc-multilib g++-multilib

      - name: Set environment variables
        run: |
          # build target for rust
          echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV

      - name: Show config for debug purposes
        run: cargo tree

      - name: Build
        run: |
          cargo build
          cargo build --release
